logging:
  level:
    org.springframework: DEBUG

spring:
  application:
    name: ms-account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://coolify.tail1270a7.ts.net:5432/pin?currentSchema=account
    username: account_user
    password: 0KbNMsFnRjwyTK1v
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        default_schema: account
  config:
    import: "classpath:application-vault.yml,vault://"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer-uri}

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: ${eureka-server}

management:
  endpoints:
    web:
      exposure:
        include: health,info

keycloak:
  server-url: https://keycloak.fuaddm.com
  realm: pin-realm
  client-id: spring-admin-client
  client-secret: KFBnZqbbskVEFgdMPs490YMNBu1pYUmL

cloudflare:
  access:
    client-id: 4b8e0f135fa1a9c574a175e48a28bcae.access
    client-secret: cfast_tkNtlnk6qfDDvFfU4xapngDaVoqsVPqcrBRcXZtP73e28124

